# coding=utf-8

HAO_WU_CHANNEL_ID = 14
FA_XIAN_CHANNEL_ID = 2
GUO_NEI_CHANNEL_ID = 1
HAI_TAO_CHANNEL_ID = 5

YOU_HUI_CHANNEL_ID_LIST = [FA_XIAN_CHANNEL_ID, GUO_NEI_CHANNEL_ID, HAI_TAO_CHANNEL_ID]
YUAN_CHUANG_CHANNEL_ID = 11

REDIS_TRACE_ID_COUNT_KEY = "trace_id_count"
STAR_DATA_RES_KEY = "star_data_res:%s"
ASSO_RULE_YH_RES_KEY = "%s.assoc_rule_rec.yh"
ASSO_RULE_YH_RES_KEY_EXPIRE = 900
ASSO_RULE_YC_RES_KEY = "%s.assoc_rule_rec.yc"
ASSO_RULE_YC_RES_KEY_EXPIRE = 900
BASE_SIMI_RES_KEY = "yh.%s.yh_sim_rec"

HAO_WU_TABLE = "topic_rec"
YOU_HUI_TABLE = "sync_youhui_primary"
YUAN_CHUANG_TABLE = "sync_yuanchuang"
ASSO_RULE_TABLE = "confidence_hour"
PRODUCT_ARTICLE = "sync_product_article"

YOU_HUI_ROW1_MIN_NUM = 1
YOU_HUI_ROW1_MAX_NUM = 10
YOU_HUI_ROW2_MIN_NUM = 1
YOU_HUI_ROW2_MAX_NUM = 10
YOU_HUI_ROW3_MIN_NUM = 1
YOU_HUI_ROW3_MAX_NUM = 10

YUAN_CHUANG_ROW1_MIN_NUM = 1
YUAN_CHUANG_ROW1_MAX_NUM = 10
YUAN_CHUANG_ROW2_MIN_NUM = 1
YUAN_CHUANG_ROW2_MAX_NUM = 10
YUAN_CHUANG_ROW3_MIN_NUM = 1
YUAN_CHUANG_ROW3_MAX_NUM = 10

HAO_WU_ROW1_MIN_NUM = 1
HAO_WU_ROW1_MAX_NUM = 10

YOU_HUI_ROW1_INSERT_YC_NUM = 3

REC_MODULE_NAME = "猜你喜欢"

REC_HAO_WU_MODULE_NAME = "热门榜单"

REC_YOU_HUI_ROW1_NAME = "相关优惠"
REC_YOU_HUI_ROW2_NAME = "看了又看"
REC_YOU_HUI_ROW3_NAME = "热门原创"

REC_YOU_HUI_ROW1_NAME2 = "相关推荐"
REC_YOU_HUI_ROW1_INSERT_POSTION1 = 3
REC_YOU_HUI_ROW1_INSERT_POSTION2 = 5


REC_YUAN_CHUANG_ROW2_NAME = "看了又看"
REC_YUAN_CHUANG_ROW3_NAME = "热门优惠"

